### ISSUE TITLE
The issue of infinite looping and file being occupied when saving as the same name.

### ISSUE THREAD

**Issue by taurusxin** [go-flac/go-flac#7] opened 2024-10-21 06:20 UTC
All the code uses the v2 library. My approach is as follows:

There is a source file 1.flac, after adding metadata with the code, using `audioFile.Save("1.flac")`, this method does not stop because it seems to be continuously editing the source file, causing the file size to keep increasing (resulting in an infinite loop).
When I change the file path, for example, `audioFile.Save("2.flac")`, it saves successfully, but since 1.flac has already been opened in ParseFile, any subsequent operations on 1.flac, such as deleting or renaming, will prompt that the file is occupied.

Suggested improvements:
Close the source file after Save(), or allow Save() to override with an empty parameter to save directly onto the source file.

---

保存为同名文件死循环及文件被占用的问题
所有的代码均使用v2库，我的做法是：
有一个源文件 1.flac，使用代码添加了元数据后，使用`audioFile.Save("1.flac")`，该方法将不会停止，因为似乎在源文件上编辑，使得文件大小一直在增长（陷入死循环）
当我改变文件路径时，例如`audioFile.Save("2.flac")`，能够保存成功，但由于在ParseFile中对1.flac已经打开，在之后对1.flac的任何操作都会提示该文件被占用，例如删除或重命名等。

建议的改进：
在`Save()` 后，关闭源文件，或者允许Save()空重载，保存在源文件上。

**Comment by eternal-flame-AD** [comment] 2024-10-21 08:01
Is this what you attempted? Open a file, edit the metadata and call `Save()` on the original file?

I can add a check and docs to disallow this but I think it is generally accepted that copying a file to itself will be undefined behavior. 

There is not a good strategy to prevent this unfortunately. Some people want me to pipe through the FLAC body transparently ref: #5  .

The issue is you do not know how much data need to be buffered. You could have grown the metadata block and I would have to calculate how much it has grown, buffer that amount , write your metadata out, buffer the next chunk of data with an offset, and then write the previous buffer, and then repeat ...

It's essentially trying to shift an array right by k elements: it's not a cheap operation and usually easier and more reliable to just make a new array and get rid of the old one.

**Comment by eternal-flame-AD** [comment] 2024-10-21 08:11
You are welcome to put in a pull request, otherwise I will fix it probably tuesday or wednesday

General idea: If the file is opened from a file, record the size of the file before doing anything, use os#SameFile to make sure the output is not the input, and copy at most the original size - parsed metadata size when calling Save()

https://pkg.go.dev/os#SameFile

**Comment by eternal-flame-AD** [comment] 2024-10-22 21:27
Fixed in https://github.com/go-flac/go-flac/releases/tag/v2.0.2

The public go doc should refresh shortly.

**Closed as completed by eternal-flame-AD** 2024-10-22 21:27 UTC
Labels: bug, enhancement
